In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from xgboost import XGBRegressor
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [ ]:
#loading the dataset
HousePrice = pd.read_csv('HousePricingPrediction.csv', header=0)

In [ ]:
HousePrice.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [ ]:
#number of rows and columns
HousePrice.shape

(4600, 18)

In [ ]:
HousePrice.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [ ]:
print(HousePrice.columns)

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [ ]:
HousePrice = HousePrice[HousePrice['price'] > 0]

In [ ]:
#seperate test
X= HousePrice.drop(['price'], axis = 1)
Y = HousePrice['price']

In [ ]:
#cleaning
X = X.drop(['date', 'street', 'country'], axis=1)
print(X)
print(Y)

      bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0          3.0       1.50         1340      7912     1.5           0     0
1          5.0       2.50         3650      9050     2.0           0     4
2          3.0       2.00         1930     11947     1.0           0     0
3          3.0       2.25         2000      8030     1.0           0     0
4          4.0       2.50         1940     10500     1.0           0     0
...        ...        ...          ...       ...     ...         ...   ...
4595       3.0       1.75         1510      6360     1.0           0     0
4596       3.0       2.50         1460      7573     2.0           0     0
4597       3.0       2.50         3010      7014     2.0           0     0
4598       4.0       2.00         2090      6630     1.0           0     0
4599       3.0       2.50         1490      8102     2.0           0     0

      condition  sqft_above  sqft_basement  yr_built  yr_renovated       city  \
0             3        1340              0      1955          2005  Shoreline
1             5        3370            280      1921             0    Seattle
2             4        1930              0      1966             0       Kent
3             4        1000           1000      1963             0   Bellevue
4             4        1140            800      1976          1992    Redmond
...         ...         ...            ...       ...           ...        ...
4595          4        1510              0      1954          1979    Seattle
4596          3        1460              0      1983          2009   Bellevue
4597          3        3010              0      2009             0     Renton
4598          3        1070           1020      1974             0    Seattle
4599          4        1490              0      1990             0  Covington

      statezip
0     WA 98133
1     WA 98119
2     WA 98042
3     WA 98008
4     WA 98052
...        ...
4595  WA 98133
4596  WA 98007
4597  WA 98059
4598  WA 98178
4599  WA 98042

[4551 rows x 14 columns]
0       3.130000e+05
1       2.384000e+06
2       3.420000e+05
3       4.200000e+05
4       5.500000e+05
            ...
4595    3.081667e+05
4596    5.343333e+05
4597    4.169042e+05
4598    2.034000e+05
4599    2.206000e+05
Name: price, Length: 4551, dtype: float64

In [ ]:
le= LabelEncoder()
X['city'] = le.fit_transform(X['city'])
X['statezip'] = le.fit_transform(X['statezip'])

In [ ]:
#Data split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Model

Thuật toán Hồi quy Tuyến tính (Linear Regression)

In [ ]:
model = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=5)
model.fit(X_train_scaled, Y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

Model Evaluation

In [ ]:
X_train_prediction = model.predict(X_train_scaled)
X_train_scaled_mse = metrics.mean_squared_error(Y_train, X_train_prediction)

In [ ]:
print('MSE score of the trainning', X_train_scaled_mse)

MSE score of the trainning 33553158138.265236

In [ ]:
X_test_prediction = model.predict(X_test_scaled)
X_test_scaled_mse = metrics.mean_squared_error(Y_test, X_test_prediction)
print('MSE score of trainning', X_test_scaled_mse)

MSE score of trainning 72614710855.44139